#pragma once

#define DISPLAY_ST77916
#define DISPLAY_COLOR_BITS 16
#define DISPLAY_PHYSICAL_RES_WIDTH 360
#define DISPLAY_PHYSICAL_RES_HEIGHT 360
#define DISPLAY_RES_WIDTH 360
#define DISPLAY_RES_HEIGHT 360
#define DISPLAY_OFFSET_X (DISPLAY_PHYSICAL_RES_WIDTH - DISPLAY_RES_WIDTH) / 2
#define DISPLAY_OFFSET_Y (DISPLAY_PHYSICAL_RES_HEIGHT - DISPLAY_RES_HEIGHT) / 2
#define DISPLAY_TOUCH_ENABLED 1
